fn main() {
    // TODO: Create an array called `a` with at least 100 elements in it.
    // let a = ???

    let a: [&str; 520] = ["a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z", "a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z","a", "b", "C","D", "E", "F","G","H","I","J", "K","L", "M", "N","O", "P", "Q","R","S","T","U","V", "W", "X", "Y", "Z",];

    if a.len() >= 100 {
        println!("Wow, that's a big array!");
    } else {
        println!("Meh, I eat arrays like that for breakfast.");
        panic!("Array not big enough, more elements needed");
    }
}
